name: Automate Job Scraping and Notifications

on:
  schedule:
    # - cron: "30 * * * *"
    - cron: "*/1 * * * *"

jobs:
  automate:
    runs-on: ubuntu-latest

    env:
      USERNAME: ${{ secrets.SMTP_USERNAME }}
      PASSWORD: ${{ secrets.SMTP_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python with Node.js
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          node-version: 16  

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Script
        run: python script.py
